(test
 (name test)
 (libraries alcotest mirage-random-test lwt.unix logs logs.fmt
   mirage-flow mirage-vnetif mirage-clock-unix pcap-format duration
   mirage-random arp arp.mirage ethernet tcpip.ipv4 tcpip.tcp tcpip.udp
   tcpip.stack-direct tcpip.icmpv4
   tcpip.stack-unix tcpip.ipv6 ipaddr-cstruct
   macaddr-cstruct tcpip)
 (action
  (run %{test} -q -e --color=always)))
